### ISSUE TITLE
Table.js:55 Error: No provider for "canvas"! (Resolving: popupMenu -> canvas)

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/dmn-js#206]
I'm upgrading from DMN 0.6.0 to 0.8.0 (Bower version) and something has changed because the last version of DMN cannot be instantiated anymore.

I've the same problem like that user: https://forum.bpmn.io/t/dmn-js-modeler-with-angular-js/1382

**The  previous DMN 0.6 version works great.**

The DMN component installed by Bower: https://github.com/bpmn-io/bower-dmn-js.git

> Table.js:54 Failed to instantiate component

```

(anonymous) @ Table.js:54
bootstrap @ Table.js:48
createInjector @ Table.js:83
Table @ Table.js:104
Viewer._init @ Viewer.js:340
Viewer @ Viewer.js:107
Modeler @ Modeler.js:107
Viewer @ Viewer.js:127
Modeler @ Modeler.js:111
initialize @ decision.js:275
link @ decision.js:297
(anonymous) @ angular.js:1341
(anonymous) @ angular.js:10413
invokeLinkFn @ angular.js:10419
nodeLinkFn @ angular.js:9808
(anonymous) @ angular.js:10147
processQueue @ angular.js:16843
(anonymous) @ angular.js:16887
$digest @ angular.js:17982
$apply @ angular.js:18280
done @ angular.js:12378
completeRequest @ angular.js:12604
requestLoaded @ angular.js:12532
Table.js:55 Error: No provider for "canvas"! (Resolving: popupMenu -> canvas)
    at error (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:28969:12)
    at Object.get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:28955:15)
    at get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29009:19)
    at http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29030:14
    at Array.map (native)
    at invoke (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29029:31)
    at Array.instantiate (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29014:20)
    at Injector.get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29003:43)
    at http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:42940:57
    at Array.forEach (native)
(anonymous) @ Table.js:55
bootstrap @ Table.js:48
createInjector @ Table.js:83
Table @ Table.js:104
Viewer._init @ Viewer.js:340
Viewer @ Viewer.js:107
Modeler @ Modeler.js:107
Viewer @ Viewer.js:127
Modeler @ Modeler.js:111
initialize @ decision.js:275
link @ decision.js:297
(anonymous) @ angular.js:1341
(anonymous) @ angular.js:10413
invokeLinkFn @ angular.js:10419
nodeLinkFn @ angular.js:9808
(anonymous) @ angular.js:10147
processQueue @ angular.js:16843
(anonymous) @ angular.js:16887
$digest @ angular.js:17982
$apply @ angular.js:18280
done @ angular.js:12378
completeRequest @ angular.js:12604
requestLoaded @ angular.js:12532
```

I'm using DMN 0.8.0 (from `https://github.com/bpmn-io/bower-dmn-js`) and Bower 1.8.0.

**Comment by rbatllet** [comment]
It seems bower-dmn-js is generated with the 0.8.0 version of DMN, but now DMN is 0.8.5

**Comment by rbatllet** [comment]
I've generated the Bower version from the last DMN sources manually, but sadly, the problem persists:

```
dmn-modeler.js:43075 Error: No provider for "canvas"! (Resolving: popupMenu -> canvas)
    at error (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29101:12)
    at Object.get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29087:15)
    at get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29141:19)
    at http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29162:14
    at Array.map (native)
    at invoke (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29161:31)
    at Array.instantiate (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29146:20)
    at Injector.get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29135:43)
    at http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:43072:57
    at Array.forEach (native)
(anonymous) @ dmn-modeler.js:43075
angular.js:14516 Error: No provider for "canvas"! (Resolving: popupMenu -> canvas)
    at error (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29101:12)
    at Object.get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29087:15)
    at get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29141:19)
    at http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29162:14
    at Array.map (native)
    at invoke (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29161:31)
    at Array.instantiate (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29146:20)
    at Injector.get (http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:29135:43)
    at http://localhost:9000/bower_components/dmn-js/dist/dmn-modeler.js:43072:57
```

**Comment by rbatllet** [comment]
I've tested the "bower-dmn-js" samples, I can confirm that tests with the Modeler does not work, but only work the tests with the Viewer.

See: https://github.com/bpmn-io/bower-dmn-js/issues/1

**Comment by rbatllet** [comment]
I think something is wrong in the Grunt "bundle:modeler" task.

**Comment by ixfr** [comment]
Same problem here :-(
The bower version seems to be 0.8.0 - so I tried to download a prebuilt newer one (0.8.4) - the link (https://bpmn.io/toolkit/dmn-js/download/) is however broken, i.e. 404 on

https://codeload.github.com/bpmn-io/bower-dmn-js/zip/v0.8.4

I suppose the issues are unrelated - it's just that the logical alternative (at least to me) doesn't help either ...

**Comment by rbatllet** [comment]
The https://bpmn.io/toolkit/dmn-js/download/ link is not broken now. You can try this link (https://github.com/bpmn-io/dmn-js) as well.

**Comment by rbatllet** [comment]
But the bower version of DMN 0.8.x is bad.

**Comment by nikku** [comment]
We can reproduce this.

**Comment by nikku** [comment]
This is a bundling issue we can easily work around: https://github.com/substack/node-browserify/issues/1450.
